#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("wkurw.Resource", IsApplication=true)]

namespace wkurw
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_email_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checkbox_style = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int kwadrat_czerwony = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int kwadrat_zielony = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int button_oblicz = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int button_znak = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int imageButton1 = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout2 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout3 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout4 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayoutimagine = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int m_View = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int switch_dodac_odjac = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int switch_dziel_mnoz = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int txt_kombi_1 = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int txt_kombi_2 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int txt_kombi_3 = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int txt_waluta_1 = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int txt_waluta_2 = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int txt_wynik = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calculator = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int close_drawer = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int open_drawer = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int ActionBar_TitleTextStyle = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int AppTheme = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int CustomTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyActionBar = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
